name: Automated tests and reports

on:
  workflow_dispatch

jobs:
  running_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Setup Chrome
        run: sudo apt-get install google-chrome-stable

      - name: Setup requirements
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest --alluredir=allure-results
        continue-on-error: true

      - name: Save allure-results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
          retention-days: 1



